# Generated by Django 3.1.1 on 2020-09-29 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=15, verbose_name='номер телефона')),
                ('email', models.CharField(max_length=50, verbose_name='почта')),
                ('city', models.CharField(max_length=20, verbose_name='город')),
                ('adress', models.TextField(blank=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='productcategory',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
    ]
