# Generated by Django 3.1.1 on 2020-09-29 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_auto_20200929_1312'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='adress',
            new_name='address',
        ),
    ]
